apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mwd93bpdf-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6a75fd1dcb.3bb1.p3.openshiftapps.com/rhtap/rhtap-qe:4645c22651a9ae778b7bb84530145690066d88fb@sha256:c43ef739d7273b38f217f4500be7ab85b5377a98b2be627997449b83a0a60461
          name: container-image
